#!/usr/bin/env bash

cabal build GetTCTraces &&
./dist/build/GetTCTraces/GetTCTraces --trades testcases/test1.txt > testcases/sink &&
diff -U -1 testcases/test1_res.txt testcases/sink | colordiff | diff-highlight
